### ISSUE TITLE
Chapter 8: Learning to tune PPO 

### ISSUE THREAD

**Issue by markus-weiss** [PacktPublishing/Hands-On-Deep-Learning-for-Games#4]
Hello,

I recived some game-breaking errors while I imported the "Reacher_3_joint.scene".  Is there any solution?  

![Reacher_joint_1](https://user-images.githubusercontent.com/37873311/71465530-303fa100-27bd-11ea-83b2-cc16867ca239.PNG)
![Reacher_joint_2](https://user-images.githubusercontent.com/37873311/71465532-30d83780-27bd-11ea-957f-1210c88d5703.PNG)

**Comment by cxbxmxcx** [comment]
These errors are most likely associated with Unity project versions. Please be sure to check the versions required by ML-Agents.
